controller_manager:
  ros__parameters:
    update_rate: 200

    head_trajectory_controller:
      type: tmc_joint_command_controller/BasicJointCommandController
    arm_trajectory_controller:
      type: tmc_joint_command_controller/BasicJointCommandController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    omni_base_controller:
      type: hsrb_base_controllers/OmniBaseController
    gripper_controller:
      type: hsrb_gripper_controller/HrhGripperController
    head_motion_command_limiter_controller:
      type: tmc_realtime_controllers/MotionCommandLimiterController
    arm_motion_command_limiter_controller:
      type: tmc_realtime_controllers/MotionCommandLimiterController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
      - head_tilt_joint
      - head_pan_joint
      - base_l_drive_wheel_joint
      - base_r_drive_wheel_joint
      - base_roll_joint
      - hand_motor_joint
      - hand_l_spring_proximal_joint
      - hand_r_spring_proximal_joint
    interfaces:
      - position
      - velocity
      - effort

head_trajectory_controller:
  ros__parameters:
    joints:
      - head_tilt_joint
      - head_pan_joint
    command_joints:
      - head_motion_command_limiter_controller/head_tilt_joint
      - head_motion_command_limiter_controller/head_pan_joint
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    use_velocity_state_for_trajectory: true
    position_control_mode: 1
    velocity_control_mode: 2

arm_trajectory_controller:
  ros__parameters:
    joints:
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
    command_joints:
      - arm_motion_command_limiter_controller/arm_lift_joint
      - arm_motion_command_limiter_controller/arm_flex_joint
      - arm_motion_command_limiter_controller/arm_roll_joint
      - arm_motion_command_limiter_controller/wrist_flex_joint
      - arm_motion_command_limiter_controller/wrist_roll_joint
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    use_velocity_state_for_trajectory: true
    position_control_mode: 1
    velocity_control_mode: 2

omni_base_controller:
  ros__parameters:
    use_base_roll_velocity: true
    model_node_name: whole_body/robot_state_publisher
    joints:
      l_wheel: base_l_drive_wheel_joint
      r_wheel: base_r_drive_wheel_joint
      steer: base_roll_joint
    wheel_odom_map_frame: odom
    wheel_odom_base_frame: base_footprint_wheel
    odometry_publish_rate: 50.0
    transform_publish_rate: 50.0
    yaw_velocity_limit: 1.8      # [rad/s]
    wheel_velocity_limit: 20.8   # [rad/s]
    base_coordinates: [odom_x, odom_y, odom_t]
    odom_x:
      p_gain: 1.0
    odom_y:
      p_gain: 1.0
    odom_t:
      p_gain: 1.0
    use_sim_time: True
    open_loop_control: True

gripper_controller:
  ros__parameters:
    use_sim_time: True
    model_node_name: whole_body/robot_state_publisher
    joints:
      - hand_motor_joint
    position_goal_tolerance: 0.2
    force_goal_tolerance: 10000.0
    left_spring_joint: hand_l_spring_proximal_joint
    right_spring_joint: hand_r_spring_proximal_joint
    open_loop_control: true
    distance_control_pgain: 2.0
    distance_control_igain: 0.0
    distance_control_dgain: 0.0
    force_control_pgain: 0.3
    force_control_igain: 0.05
    force_control_dgain: 0.4

head_motion_command_limiter_controller:
  ros__parameters:
    joint_names:
      - head_pan_joint
      - head_tilt_joint
    control_mode_switching: true
    position_control_mode: 1
    velocity_control_mode: 2

arm_motion_command_limiter_controller:
  ros__parameters:
    joint_names:
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
    control_mode_switching: true
    position_control_mode: 1
    velocity_control_mode: 2