omni_base_controller:
  ros__parameters:
    yaw_velocity_limit: 1.8
    wheel_velocity_limit: 8.5

motion_command_limiter_controller:
  ros__parameters:
    base_l_drive_wheel_joint:
      use_command_velocity: true
      acceleration_limit: 41.7
    base_r_drive_wheel_joint:
      use_command_velocity: true
      acceleration_limit: 41.7
    base_roll_joint:
      use_command_velocity: true
      acceleration_limit: 5.0
