controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    head_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    omni_base_controller:
      type: hsrb_base_controllers/OmniBaseController

head_trajectory_controller:
  ros__parameters:
    joints:
      - head_tilt_joint
      - head_pan_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true

arm_trajectory_controller:
  ros__parameters:
    joints:
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true

omni_base_controller:
  ros__parameters:
    joints:
      l_wheel: base_l_drive_wheel_joint
      r_wheel: base_r_drive_wheel_joint
      steer: base_roll_joint
    wheel_odom_map_frame: odom
    wheel_odom_base_frame: base_footprint_wheel
    odometry_publish_rate: 50.0
    transform_publish_rate: 50.0
    yaw_velocity_limit: 1.8
    wheel_velocity_limit: 20.0
    base_coordinates: [odom_x, odom_y, odom_t]
    odom_x: {p_gain: 1.0}
    odom_y: {p_gain: 1.0}
    odom_t: {p_gain: 1.0}
    constraints:
      stopped_velocity_tolerance: 0.0
      odom_x: {trajectory: 0.05}
      odom_y: {trajectory: 0.05}
      odom_t: {trajectory: 0.1}

