cmake_minimum_required(VERSION 3.5)
project(hsrb_gz_ros2_control)

# Compiler options
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    add_compile_options(-Wall -Wextra -Wpedantic)
endif()

# Find dependencies
find_package(ament_cmake REQUIRED)
find_package(gz_ros2_control REQUIRED)
find_package(hardware_interface REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp_lifecycle REQUIRED)
find_package(tmc_exxx_servo_motor_protocol REQUIRED)

find_package(gz_sim_vendor REQUIRED)
find_package(gz-sim REQUIRED)

find_package(gz_plugin_vendor REQUIRED)
find_package(gz-plugin REQUIRED)

include_directories(include)

add_library(hsrb_hardware_plugins SHARED
  src/hsrb_system.cpp
)
ament_target_dependencies(hsrb_hardware_plugins
  gz_ros2_control
  hardware_interface
  pluginlib
  rclcpp_lifecycle
  tmc_exxx_servo_motor_protocol
)
target_link_libraries(hsrb_hardware_plugins
  gz-sim::gz-sim
)

install(DIRECTORY
  include/
  DESTINATION include
)

# Testing and linting
if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
endif()

ament_export_include_directories(include)
ament_export_libraries(hsrb_hardware_plugins)

pluginlib_export_plugin_description_file(gz_ros2_control gz_hardware_plugins.xml)

## Install
install(
  TARGETS hsrb_hardware_plugins
  EXPORT export_${PROJECT_NAME}
  ARCHIVE DESTINATION lib
  LIBRARY DESTINATION lib
  RUNTIME DESTINATION bin
)
ament_export_dependencies(
  gz_ros2_control
  hardware_interface
  pluginlib
  rclcpp_lifecycle
  tmc_exxx_servo_motor_protocol
)

# Setup the project
ament_package()
